import { UserProvider } from '@/lib/auth'
import { getUser } from '@/lib/db/queries'
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import localFont from 'next/font/local'
import GlobalNav from './components/global-nav'
import './globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`min-h-dvh bg-backgroundMud text-black antialiased dark:text-white ${geistSans.variable} ${geistMono.variable}`}
      >
        <ThemeProvider>
          <UserProvider userPromise={getUser()}>
            <main className="relative flex min-h-dvh w-full bg-backgroundMud p-4 md:pl-28">
              <GlobalNav />
              {children}
            </main>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
